name: Add Comment to Issue

on:
  issues:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add report to the issue as a comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body-path: 'generated_reports/test_summarize_to_30_words.md'
